name: oms
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  sqflite: any
  path_provider: any
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  loading_animations: "^2.1.0"
  flutter_datetime_picker: ^1.5.1
  flutter_easyloading: ^3.0.5
  #rounded_loading_button: 2.0.8
  rounded_loading_button:
    git:
      url: https://github.com/scopendo/flutter_rounded_loading_button.git
      ref: master
  flutter_lints: 3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - android/assets/logo.png
    - android/assets/person.png
    - android/assets/search.png
    - android/assets/landingImg.png
    - android/assets/landing.png
    - android/assets/outage.png
    - android/assets/attend.png
    - android/assets/service.png
    - android/assets/pylons.jpg
    - android/assets/abort.png
